name: Bumps-v2
on: 
  workflow_dispatch:
    inputs:
      new_version: 
        description: New project version. Defaults to bumping minor version.
        required: false
jobs:
  commit-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      # - uses: ./.github/actions/my-action
      - name: Infer new version
        run: |
          NEW_VERSION_ARG="${{ github.event.inputs.new_version }}"
          if [ -n "$NEW_VERSION_ARG" ]; then
            NEW_VERSION="$NEW_VERSION_ARG"
          else
            VERSION_PATH="${{ github.workspace }}/VERSION"
            echo "version path: $VERSION_PATH"
            echo "pwd: $PWD"

            MAJOR=$(sed -r 's/^([0-9]+)\.([0-9]+)\.([0-9]+)(-.+)?$/\1/' $VERSION_PATH)
            MINOR=$(sed -r 's/^([0-9]+)\.([0-9]+)\.([0-9]+)(-.+)?$/\2/' $VERSION_PATH)
            PATCH=$(sed -r 's/^([0-9]+)\.([0-9]+)\.([0-9]+)(-.+)?$/\3/' $VERSION_PATH)
            DEV=$(sed -r 's/^([0-9]+)\.([0-9]+)\.([0-9]+)(-.+)?$/\4/' $VERSION_PATH)
            echo "current version is $MAJOR.$MINOR.$PATCH.$DEV"

            NEW_VERSION="$MAJOR.$(expr $MINOR + 1).$PATCH"
          fi

          echo "after the bump this will be $NEW_VERSION"
          echo $NEW_VERSION > $VERSION_PATH

          git config --local user.email "action@github.com"
          git config --local user.name "Github Action on behalf of ${{ github.actor }}"
          git add $VERSION_PATH
          git commit -m "Bump version"
